/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cb3;

import Model.Anggota;
import Model.Buku;
import Model.LoginModel;
import Model.Perpustakaan;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    private Perpustakaan app;
    
    public MainView() {
        app = new Perpustakaan();
        
        initComponents();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(loginPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        daftarBukuButton = new javax.swing.JButton();
        tambahBukuButton = new javax.swing.JButton();
        tambahAnggotaButton = new javax.swing.JButton();
        pinjamBukuButton = new javax.swing.JButton();
        kembalikanBukuButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        daftarBukuPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBukuTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        judulDetailLabel = new javax.swing.JLabel();
        genreDetailLabel = new javax.swing.JLabel();
        deskripsiDetailLabel = new javax.swing.JLabel();
        statusDetailLabel = new javax.swing.JLabel();
        hapusButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tampilkanDetailButton = new javax.swing.JButton();
        judulDetailField = new javax.swing.JTextField();
        genreDetailField = new javax.swing.JTextField();
        statusDetailField = new javax.swing.JTextField();
        deskripsiDetailField = new javax.swing.JTextField();
        tambahBukuPanel = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        judulField = new javax.swing.JTextField();
        tahunTerbitField = new javax.swing.JTextField();
        genreField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        sinopsisTextArea = new javax.swing.JTextArea();
        tambahkanBukuButton = new javax.swing.JButton();
        tambahAnggotaPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        tambahkanAnggotaButton = new javax.swing.JButton();
        pinjamBukuPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bukuTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        anggotaTable = new javax.swing.JTable();
        bukuLabel = new javax.swing.JLabel();
        anggotaLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        judulBukuLabel = new javax.swing.JLabel();
        pinjamButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        namaSearchField = new javax.swing.JTextField();
        kembalikanBukuPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelAnggotaTable = new javax.swing.JTable();
        namaSearchField1 = new javax.swing.JTextField();
        namaLabel1 = new javax.swing.JLabel();
        anggotaLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        judulBuku1Label = new javax.swing.JLabel();
        waktuKembali1Label = new javax.swing.JLabel();
        cekBuku1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        judulBuku2Label = new javax.swing.JLabel();
        waktuKembali2Label = new javax.swing.JLabel();
        cekBuku2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        judulBuku3Label = new javax.swing.JLabel();
        waktuKembali3Label = new javax.swing.JLabel();
        cekBuku3 = new javax.swing.JCheckBox();
        tampilkanBukuButton = new javax.swing.JButton();
        tombolKembalikanBukuButton = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        daftarBukuButton.setText("Daftar buku");
        daftarBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBukuButtonActionPerformed(evt);
            }
        });

        tambahBukuButton.setText("Tambah Buku");
        tambahBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBukuButtonActionPerformed(evt);
            }
        });

        tambahAnggotaButton.setText("Tambah Anggota");
        tambahAnggotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahAnggotaButtonActionPerformed(evt);
            }
        });

        pinjamBukuButton.setText("Pinjam Buku");
        pinjamBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamBukuButtonActionPerformed(evt);
            }
        });

        kembalikanBukuButton.setText("Kembalikan Buku");
        kembalikanBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalikanBukuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(daftarBukuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahBukuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahAnggotaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pinjamBukuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kembalikanBukuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(daftarBukuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahBukuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahAnggotaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pinjamBukuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kembalikanBukuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelBukuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Judul Buku", "Genre", "Sinopsis", "Status Pinjam"
            }
        ));
        jScrollPane1.setViewportView(tabelBukuTable);

        jLabel1.setText("Daftar Buku");

        jLabel2.setText("Cari buku");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        judulDetailLabel.setText("[Judul]");

        genreDetailLabel.setText("[Jenis/Genre]");

        deskripsiDetailLabel.setText("[Deskripsi/Sinopsis]");

        statusDetailLabel.setText("[Status pinjam]");

        hapusButton.setText("Hapus Buku");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tampilkanDetailButton.setText("Tampilkan Detail ");
        tampilkanDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanDetailButtonActionPerformed(evt);
            }
        });

        judulDetailField.setText("jTextField2");

        genreDetailField.setText("jTextField3");

        statusDetailField.setText("jTextField5");

        deskripsiDetailField.setText("jTextField2");

        javax.swing.GroupLayout daftarBukuPanelLayout = new javax.swing.GroupLayout(daftarBukuPanel);
        daftarBukuPanel.setLayout(daftarBukuPanelLayout);
        daftarBukuPanelLayout.setHorizontalGroup(
            daftarBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarBukuPanelLayout.createSequentialGroup()
                .addGroup(daftarBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daftarBukuPanelLayout.createSequentialGroup()
                        .addGroup(daftarBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(daftarBukuPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addGroup(daftarBukuPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addGroup(daftarBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daftarBukuPanelLayout.createSequentialGroup()
                        .addComponent(hapusButton)
                        .addGap(129, 129, 129))
                    .addGroup(daftarBukuPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(daftarBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulDetailField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusDetailLabel)
                            .addComponent(genreDetailLabel)
                            .addComponent(judulDetailLabel)
                            .addComponent(deskripsiDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tampilkanDetailButton)
                            .addComponent(statusDetailField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deskripsiDetailField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genreDetailField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        daftarBukuPanelLayout.setVerticalGroup(
            daftarBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daftarBukuPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(daftarBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampilkanDetailButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(34, 34, 34)
                .addGroup(daftarBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(daftarBukuPanelLayout.createSequentialGroup()
                        .addComponent(judulDetailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(judulDetailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genreDetailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genreDetailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deskripsiDetailLabel)
                        .addGap(9, 9, 9)
                        .addComponent(deskripsiDetailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusDetailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusDetailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(hapusButton)
                        .addGap(16, 16, 16)))
                .addGap(31, 31, 31))
        );

        judulLabel.setText("Judul :");

        jLabel12.setText("Tahun Terbit :");

        jLabel13.setText("Genre :");

        jLabel14.setText("Sinopsis : ");

        sinopsisTextArea.setColumns(20);
        sinopsisTextArea.setRows(5);
        jScrollPane2.setViewportView(sinopsisTextArea);

        tambahkanBukuButton.setText("Tambahkan Buku");
        tambahkanBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkanBukuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahBukuPanelLayout = new javax.swing.GroupLayout(tambahBukuPanel);
        tambahBukuPanel.setLayout(tambahBukuPanelLayout);
        tambahBukuPanelLayout.setHorizontalGroup(
            tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBukuPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tambahkanBukuButton)
                    .addGroup(tambahBukuPanelLayout.createSequentialGroup()
                        .addGroup(tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(judulLabel)
                            .addComponent(jLabel12))
                        .addGap(41, 41, 41)
                        .addGroup(tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(genreField)
                                .addComponent(tahunTerbitField)
                                .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tambahBukuPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        tambahBukuPanelLayout.setVerticalGroup(
            tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBukuPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judulLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahunTerbitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(14, 14, 14)
                .addGroup(tambahBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tambahBukuPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel14)))
                .addGap(77, 77, 77)
                .addComponent(tambahkanBukuButton)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jLabel9.setText("First Name :");

        jLabel10.setText("Last Name :");

        jLabel11.setText("Address :");

        tambahkanAnggotaButton.setText("Tambahkan Anggota");
        tambahkanAnggotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkanAnggotaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahAnggotaPanelLayout = new javax.swing.GroupLayout(tambahAnggotaPanel);
        tambahAnggotaPanel.setLayout(tambahAnggotaPanelLayout);
        tambahAnggotaPanelLayout.setHorizontalGroup(
            tambahAnggotaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahAnggotaPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(tambahAnggotaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tambahkanAnggotaButton)
                    .addGroup(tambahAnggotaPanelLayout.createSequentialGroup()
                        .addGroup(tambahAnggotaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(tambahAnggotaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameField)
                            .addComponent(lastNameField)
                            .addComponent(addressField, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        tambahAnggotaPanelLayout.setVerticalGroup(
            tambahAnggotaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahAnggotaPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(tambahAnggotaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tambahAnggotaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(tambahAnggotaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(tambahkanAnggotaButton)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        bukuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Judul", "Tahun Terbit", "Genre", "Status Pinjam"
            }
        ));
        jScrollPane3.setViewportView(bukuTable);

        anggotaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Depan", "Nama Belakang", "Alamat"
            }
        ));
        jScrollPane4.setViewportView(anggotaTable);

        bukuLabel.setText("Buku");

        anggotaLabel.setText("Anggota");

        namaLabel.setText("Nama :");

        judulBukuLabel.setText("Judul Buku :");

        pinjamButton.setText("Pinjam");
        pinjamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamButtonActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        namaSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaSearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pinjamBukuPanelLayout = new javax.swing.GroupLayout(pinjamBukuPanel);
        pinjamBukuPanel.setLayout(pinjamBukuPanelLayout);
        pinjamBukuPanelLayout.setHorizontalGroup(
            pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinjamBukuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pinjamButton)
                .addGap(62, 62, 62))
            .addGroup(pinjamBukuPanelLayout.createSequentialGroup()
                .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pinjamBukuPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(anggotaLabel))
                    .addGroup(pinjamBukuPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pinjamBukuPanelLayout.createSequentialGroup()
                                .addComponent(namaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(namaSearchField))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinjamBukuPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(bukuLabel)
                        .addGap(109, 109, 109))
                    .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pinjamBukuPanelLayout.createSequentialGroup()
                            .addComponent(judulBukuLabel)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pinjamBukuPanelLayout.setVerticalGroup(
            pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinjamBukuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bukuLabel)
                    .addComponent(anggotaLabel))
                .addGap(19, 19, 19)
                .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namaLabel)
                        .addComponent(namaSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(judulBukuLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(pinjamButton)
                .addGap(38, 38, 38))
        );

        tabelAnggotaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Depan", "Nama Belakang", "Alamat"
            }
        ));
        jScrollPane5.setViewportView(tabelAnggotaTable);

        namaSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaSearchField1ActionPerformed(evt);
            }
        });

        namaLabel1.setText("Nama :");

        anggotaLabel1.setText("Anggota");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buku 1"));

        judulBuku1Label.setText("Judul : -");
        judulBuku1Label.setToolTipText("");

        waktuKembali1Label.setText("Tenggat Pengembailan :");

        cekBuku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBuku1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(judulBuku1Label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waktuKembali1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cekBuku1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(judulBuku1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktuKembali1Label)
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cekBuku1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buku 2"));

        judulBuku2Label.setText("Judul : -");

        waktuKembali2Label.setText("Tenggat Pengembailan :");

        cekBuku2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBuku2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(judulBuku2Label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(waktuKembali2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(cekBuku2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulBuku2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktuKembali2Label)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cekBuku2)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buku 3"));

        judulBuku3Label.setText("Judul : -");

        waktuKembali3Label.setText("Tenggat Pengembailan :");

        cekBuku3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBuku3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(judulBuku3Label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(waktuKembali3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cekBuku3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulBuku3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(waktuKembali3Label)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cekBuku3)
                .addContainerGap())
        );

        tampilkanBukuButton.setText("Tampilkan Buku Pinjaman");
        tampilkanBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanBukuButtonActionPerformed(evt);
            }
        });

        tombolKembalikanBukuButton.setText("Kembalikan Buku");
        tombolKembalikanBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKembalikanBukuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kembalikanBukuPanelLayout = new javax.swing.GroupLayout(kembalikanBukuPanel);
        kembalikanBukuPanel.setLayout(kembalikanBukuPanelLayout);
        kembalikanBukuPanelLayout.setHorizontalGroup(
            kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembalikanBukuPanelLayout.createSequentialGroup()
                .addGroup(kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tampilkanBukuButton)
                    .addGroup(kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kembalikanBukuPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(kembalikanBukuPanelLayout.createSequentialGroup()
                                    .addComponent(namaLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(namaSearchField1))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(kembalikanBukuPanelLayout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(anggotaLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombolKembalikanBukuButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kembalikanBukuPanelLayout.setVerticalGroup(
            kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembalikanBukuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anggotaLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kembalikanBukuPanelLayout.createSequentialGroup()
                        .addGroup(kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaLabel1)
                            .addComponent(namaSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kembalikanBukuPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tampilkanBukuButton)
                    .addComponent(tombolKembalikanBukuButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(daftarBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tambahBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(tambahAnggotaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(pinjamBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(24, 24, 24)))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(kembalikanBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(daftarBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tambahBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(tambahAnggotaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(pinjamBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(24, 24, 24)))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(kembalikanBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
        );

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        usernameLabel.setText("Username");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        passwordLabel.setText("Password");

        loginButton.setText("Log in");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        loginLabel.setText("Log in");
        loginLabel.setToolTipText("");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(loginLabel))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginButton)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameLabel)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordLabel)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(loginLabel)
                .addGap(46, 46, 46)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(loginButton)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String user = usernameField.getText();
        String pass =passwordField.getText();
        LoginModel creds = new LoginModel(user, pass);
        creds.login(this, mainPanel, contentPanel, dashboardPanel, contentPanel);
        /*if (usernameField.getText().equals("admin") && passwordField.getText().equals("admin")){
            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(dashboardPanel);
            mainPanel.repaint();
            mainPanel.revalidate();

            contentPanel.removeAll();
            contentPanel.repaint();
            contentPanel.revalidate();

            contentPanel.add(daftarBukuPanel);
            contentPanel.repaint();
            contentPanel.revalidate();

            DefaultTableModel modelBuku = (DefaultTableModel) tabelBukuTable.getModel();
            modelBuku.setRowCount(0);
            for (int i = 0; i < app.GetDaftarBuku().size(); i++){
                modelBuku.addRow(new Object[] {app.GetDaftarBuku().get(i).GetJudulBuku(), 
                    app.GetDaftarBuku().get(i).GetGenre(), 
                    app.GetDaftarBuku().get(i).GetDeskripsi(),
                    app.GetDaftarBuku().get(i).GetStatusPinjam()});
            }
        }else{
            JOptionPane .showMessageDialog(this,"Username : admin\nPassword : admin");
        }*/
    }//GEN-LAST:event_loginButtonActionPerformed

    private void daftarBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBukuButtonActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(daftarBukuPanel);
        contentPanel.repaint();
        contentPanel.revalidate();
        
        DefaultTableModel modelBuku = (DefaultTableModel) tabelBukuTable.getModel();
        modelBuku.setRowCount(0);
        for (int i = 0; i < app.GetDaftarBuku().size(); i++){
            modelBuku.addRow(new Object[] {app.GetDaftarBuku().get(i).GetJudulBuku(), 
                app.GetDaftarBuku().get(i).GetGenre(), 
                app.GetDaftarBuku().get(i).GetDeskripsi(),
                app.GetDaftarBuku().get(i).GetStatusPinjam()});
        }
    }//GEN-LAST:event_daftarBukuButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tambahBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBukuButtonActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(tambahBukuPanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_tambahBukuButtonActionPerformed

    private void tambahAnggotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahAnggotaButtonActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(tambahAnggotaPanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_tambahAnggotaButtonActionPerformed

    private void tambahkanAnggotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkanAnggotaButtonActionPerformed
        // TODO add your handling code here:
        String namaDepan = firstNameField.getText();
        String namaBelakang = lastNameField.getText();
        String alamat = addressField.getText();
        
        String out = app.TambahAnggota(namaDepan, namaBelakang, alamat);
        JOptionPane .showMessageDialog(this,out);
    }//GEN-LAST:event_tambahkanAnggotaButtonActionPerformed

    private void tambahkanBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkanBukuButtonActionPerformed
        // TODO add your handling code here:
        String judul = judulField.getText();
        String tahunTerbit = tahunTerbitField.getText();
        String genre = genreField.getText();
        String sinopsis = sinopsisTextArea.getText();
        
        String out = app.TambahBuku(judul, tahunTerbit, genre, sinopsis);
        JOptionPane .showMessageDialog(this,out);
    }//GEN-LAST:event_tambahkanBukuButtonActionPerformed

    private void pinjamBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamBukuButtonActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(pinjamBukuPanel);
        contentPanel.repaint();
        contentPanel.revalidate();
        
        DefaultTableModel modelBuku = (DefaultTableModel) bukuTable.getModel();
        modelBuku.setRowCount(0);
        for (int i = 0; i < app.GetDaftarBuku().size(); i++){
                modelBuku.addRow(new Object[] {app.GetDaftarBuku().get(i).GetJudulBuku(), 
                    app.GetDaftarBuku().get(i).GetTahunTerbit(), 
                    app.GetDaftarBuku().get(i).GetGenre(),
                    app.GetDaftarBuku().get(i).GetStatusPinjam()});
        }
        
        DefaultTableModel modelAnggota = (DefaultTableModel) anggotaTable.getModel();
        modelAnggota.setRowCount(0);
        for (int i = 0; i < app.GetDaftarAnggota().size(); i++){
                modelAnggota.addRow(new Object[] {app.GetDaftarAnggota().get(i).GetIdAnggota(), 
                    app.GetDaftarAnggota().get(i).GetFirstName(), 
                    app.GetDaftarAnggota().get(i).GetLastName(),
                    app.GetDaftarAnggota().get(i).GetAddress()});
        }
    }//GEN-LAST:event_pinjamBukuButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            FileInputStream fileBuku = new FileInputStream("file_buku.txt");
            ObjectInputStream inputBuku = new ObjectInputStream(fileBuku);
            
            FileInputStream fileAnggota = new FileInputStream("file_anggota.txt");
            ObjectInputStream inputAnggota = new ObjectInputStream(fileAnggota);
            
            app.SetDaftarBuku((ArrayList<Buku>)inputBuku.readObject());
            app.SetDaftarAnggota((ArrayList<Anggota>)inputAnggota.readObject());
            
            inputBuku.close();
            inputAnggota.close();
            fileBuku.close();
            fileAnggota.close();
        }catch(Exception e){
            System.out.println(e.toString());
            System.exit(1);
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try{
            FileOutputStream fileBuku = new FileOutputStream("file_buku.txt");
            ObjectOutputStream outputBuku = new ObjectOutputStream(fileBuku);
            
            FileOutputStream fileAnggota = new FileOutputStream("file_anggota.txt");
            ObjectOutputStream outputAnggota = new ObjectOutputStream(fileAnggota);
            
            outputBuku.writeObject(app.GetDaftarBuku()); //new ArrayList<Buku>()             app.GetDaftarBuku()
            outputAnggota.writeObject(app.GetDaftarAnggota()); //new ArrayList<Anggota>()    app.GetDaftarAnggota()
            
            outputBuku.close();
            fileBuku.close();
            outputAnggota.close();
            fileAnggota.close();
        }catch(Exception e){
            System.out.println(e.toString());
            System.exit(1);
        }
    }//GEN-LAST:event_formWindowClosing

    private void kembalikanBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalikanBukuButtonActionPerformed
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(kembalikanBukuPanel);
        contentPanel.repaint();
        contentPanel.revalidate();
        
        DefaultTableModel modelAnggota = (DefaultTableModel) tabelAnggotaTable.getModel();
        modelAnggota.setRowCount(0);
        for (int i = 0; i < app.GetDaftarAnggota().size(); i++){
                modelAnggota.addRow(new Object[] {app.GetDaftarAnggota().get(i).GetIdAnggota(), 
                    app.GetDaftarAnggota().get(i).GetFirstName(), 
                    app.GetDaftarAnggota().get(i).GetLastName(),
                    app.GetDaftarAnggota().get(i).GetAddress()});
        }
    }//GEN-LAST:event_kembalikanBukuButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelBuku = (DefaultTableModel) tabelBukuTable.getModel();
        int row = tabelBukuTable.getSelectedRow();
        
        if (row != -1){
            String judulBuku = modelBuku.getValueAt(row, 0).toString();
            String out = app.HapusBuku(judulBuku);
            JOptionPane.showMessageDialog(this,out);
            modelBuku.removeRow(row);
        }else{
            JOptionPane.showMessageDialog(this,"Silahkan pilih buku yang akan dihapus.");
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tampilkanDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanDetailButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelBuku = (DefaultTableModel) tabelBukuTable.getModel();
        int row = tabelBukuTable.getSelectedRow();
        judulDetailField.setText(modelBuku.getValueAt(row, 0).toString());
        genreDetailField.setText(modelBuku.getValueAt(row, 1).toString());
        deskripsiDetailField.setText(modelBuku.getValueAt(row, 2).toString());
        statusDetailField.setText(modelBuku.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tampilkanDetailButtonActionPerformed

    private void namaSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaSearchFieldActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelAnggota = (DefaultTableModel) anggotaTable.getModel();
        modelAnggota.setRowCount(0);
        for (int i = 0; i < app.GetDaftarAnggota().size(); i++){
            String nama = app.GetDaftarAnggota().get(i).GetFirstName()+" "+app.GetDaftarAnggota().get(i).GetLastName();
            if (namaSearchField.getText().contains(nama) ||
                    nama.contains(namaSearchField.getText())){
                modelAnggota.addRow(new Object[] {app.GetDaftarAnggota().get(i).GetIdAnggota(), 
                    app.GetDaftarAnggota().get(i).GetFirstName(), 
                    app.GetDaftarAnggota().get(i).GetLastName(),
                    app.GetDaftarAnggota().get(i).GetAddress()});
            }
        }
    }//GEN-LAST:event_namaSearchFieldActionPerformed

    private void pinjamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelBuku = (DefaultTableModel) bukuTable.getModel();
        int rowBuku = bukuTable.getSelectedRow();
        DefaultTableModel modelAnggota = (DefaultTableModel) anggotaTable.getModel();
        int rowAnggota = anggotaTable.getSelectedRow();
        if (rowBuku != -1 && rowAnggota != -1){
            String peminjam = modelAnggota.getValueAt(rowAnggota, 1).toString() + " " + modelAnggota.getValueAt(rowAnggota, 2).toString();
            String judul = modelBuku.getValueAt(rowBuku, 0).toString();
            String out = app.PinjamBuku(peminjam, judul);    
            JOptionPane.showMessageDialog(this,out);
        }else{
            JOptionPane.showMessageDialog(this,"Silahkan pilih buku dan anggota.");
        }
        
    }//GEN-LAST:event_pinjamButtonActionPerformed

    private void namaSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaSearchField1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelAnggota = (DefaultTableModel) tabelAnggotaTable.getModel();
        modelAnggota.setRowCount(0);
        for (int i = 0; i < app.GetDaftarAnggota().size(); i++){
            String nama = app.GetDaftarAnggota().get(i).GetFirstName()+" "+app.GetDaftarAnggota().get(i).GetLastName();
            if (namaSearchField1.getText().contains(nama) ||
                    nama.contains(namaSearchField1.getText())){
                modelAnggota.addRow(new Object[] {app.GetDaftarAnggota().get(i).GetIdAnggota(), 
                    app.GetDaftarAnggota().get(i).GetFirstName(), 
                    app.GetDaftarAnggota().get(i).GetLastName(),
                    app.GetDaftarAnggota().get(i).GetAddress()});
            }
        }
    }//GEN-LAST:event_namaSearchField1ActionPerformed

    private void cekBuku2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBuku2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cekBuku2ActionPerformed

    private void cekBuku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBuku1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cekBuku1ActionPerformed

    private void cekBuku3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBuku3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cekBuku3ActionPerformed

    private void tampilkanBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanBukuButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelAnggota = (DefaultTableModel) tabelAnggotaTable.getModel();
        int rowAnggota = tabelAnggotaTable.getSelectedRow();
        String peminjam = modelAnggota.getValueAt(rowAnggota, 1).toString()+ " " + modelAnggota.getValueAt(rowAnggota, 2).toString();
        Anggota anggota = app.GetDaftarAnggota().get(app.CariAnggota(peminjam));
        if (!anggota.GetBukuPinjaman().isEmpty()){
            judulBuku1Label.setText("Buku : "+anggota.GetBukuPinjaman().get(0).GetJudulBuku());
            waktuKembali1Label.setText("Waktu Kembali : "+anggota.GetBukuPinjaman().get(0).GetWaktuKembali());
        }else{
            judulBuku1Label.setText("Buku : -");
            waktuKembali1Label.setText("Waktu Kembali : -");
        }
        if (anggota.GetBukuPinjaman().size()>1){
            judulBuku2Label.setText("Buku : "+anggota.GetBukuPinjaman().get(1).GetJudulBuku());
            waktuKembali2Label.setText("Waktu Kembali : "+anggota.GetBukuPinjaman().get(1).GetWaktuKembali());
        }else{
            judulBuku2Label.setText("Buku : -");
            waktuKembali2Label.setText("Waktu Kembali : -");
        }
        if (anggota.GetBukuPinjaman().size()>2){
            judulBuku3Label.setText("Buku : "+anggota.GetBukuPinjaman().get(2).GetJudulBuku());
            waktuKembali3Label.setText("Waktu Kembali : "+anggota.GetBukuPinjaman().get(2).GetWaktuKembali());
        }else{
            judulBuku3Label.setText("Buku : -");
            waktuKembali3Label.setText("Waktu Kembali : -");
        }
    }//GEN-LAST:event_tampilkanBukuButtonActionPerformed

    private void tombolKembalikanBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKembalikanBukuButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelAnggota = (DefaultTableModel) tabelAnggotaTable.getModel();
        int rowAnggota = tabelAnggotaTable.getSelectedRow();
        
        String peminjam = modelAnggota.getValueAt(rowAnggota, 1).toString()+ " " + modelAnggota.getValueAt(rowAnggota, 2).toString();
        Anggota anggota = app.GetDaftarAnggota().get(app.CariAnggota(peminjam));
        
        if (tabelAnggotaTable.getSelectedRow() != -1 && (cekBuku1.isSelected()||cekBuku2.isSelected()||cekBuku3.isSelected())){
            if(cekBuku3.isSelected()&&anggota.GetBukuPinjaman().size()>2){
                app.KembalikanBuku(peminjam, anggota.GetBukuPinjaman().get(2).GetJudulBuku());
            }
            if(cekBuku2.isSelected()&&anggota.GetBukuPinjaman().size()>1){
                app.KembalikanBuku(peminjam, anggota.GetBukuPinjaman().get(1).GetJudulBuku());
            }
            if(cekBuku1.isSelected()&&anggota.GetBukuPinjaman().size()>0){
                app.KembalikanBuku(peminjam, anggota.GetBukuPinjaman().get(0).GetJudulBuku());
            }
            JOptionPane.showMessageDialog(this,"Semua buku telah dikembalikan.");
        }else{
            JOptionPane.showMessageDialog(this,"Silahkan pilih peminjam dan buku yang akan dikembalikan.");
        }
    }//GEN-LAST:event_tombolKembalikanBukuButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel anggotaLabel;
    private javax.swing.JLabel anggotaLabel1;
    private javax.swing.JTable anggotaTable;
    private javax.swing.JLabel bukuLabel;
    private javax.swing.JTable bukuTable;
    private javax.swing.JCheckBox cekBuku1;
    private javax.swing.JCheckBox cekBuku2;
    private javax.swing.JCheckBox cekBuku3;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton daftarBukuButton;
    private javax.swing.JPanel daftarBukuPanel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JTextField deskripsiDetailField;
    private javax.swing.JLabel deskripsiDetailLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField genreDetailField;
    private javax.swing.JLabel genreDetailLabel;
    private javax.swing.JTextField genreField;
    private javax.swing.JButton hapusButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel judulBuku1Label;
    private javax.swing.JLabel judulBuku2Label;
    private javax.swing.JLabel judulBuku3Label;
    private javax.swing.JLabel judulBukuLabel;
    private javax.swing.JTextField judulDetailField;
    private javax.swing.JLabel judulDetailLabel;
    private javax.swing.JTextField judulField;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton kembalikanBukuButton;
    private javax.swing.JPanel kembalikanBukuPanel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaLabel1;
    private javax.swing.JTextField namaSearchField;
    private javax.swing.JTextField namaSearchField1;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton pinjamBukuButton;
    private javax.swing.JPanel pinjamBukuPanel;
    private javax.swing.JButton pinjamButton;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JTextArea sinopsisTextArea;
    private javax.swing.JTextField statusDetailField;
    private javax.swing.JLabel statusDetailLabel;
    private javax.swing.JTable tabelAnggotaTable;
    private javax.swing.JTable tabelBukuTable;
    private javax.swing.JTextField tahunTerbitField;
    private javax.swing.JButton tambahAnggotaButton;
    private javax.swing.JPanel tambahAnggotaPanel;
    private javax.swing.JButton tambahBukuButton;
    private javax.swing.JPanel tambahBukuPanel;
    private javax.swing.JButton tambahkanAnggotaButton;
    private javax.swing.JButton tambahkanBukuButton;
    private javax.swing.JButton tampilkanBukuButton;
    private javax.swing.JButton tampilkanDetailButton;
    private javax.swing.JButton tombolKembalikanBukuButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel waktuKembali1Label;
    private javax.swing.JLabel waktuKembali2Label;
    private javax.swing.JLabel waktuKembali3Label;
    // End of variables declaration//GEN-END:variables
}
